# Generated by Django 4.0.6 on 2022-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопросы клиентов',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
