# Generated by Django 4.0.6 on 2022-07-21 22:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description', models.CharField(max_length=50, verbose_name='Название описания')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст описания')),
            ],
            options={
                'verbose_name': 'Описания',
                'verbose_name_plural': 'Описании',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.CharField(max_length=50, verbose_name='Названия изображения')),
                ('image', models.ImageField(upload_to='sliderimg/', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображении',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slider', models.CharField(max_length=50, verbose_name='Названия слайдера')),
                ('description', models.ManyToManyField(to='pages.description', verbose_name='Описания')),
                ('images', models.ManyToManyField(to='pages.image', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
