# Generated by Django 4.0.6 on 2022-07-21 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_description_page_image_page_slider_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Страница'),
        ),
    ]
