# Generated by Django 4.0.6 on 2022-07-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_description_page_alter_image_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='type_description',
            field=models.CharField(choices=[('TI', 'Title'), ('TE', 'Text')], default='TI', max_length=2),
        ),
    ]
