# Generated by Django 4.0.6 on 2022-07-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_description_type_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type_image',
            field=models.CharField(choices=[('Jpg', 'JPG'), ('Webp', 'WEBP')], default='Jpg', max_length=4, verbose_name='Расширение файла'),
        ),
    ]
