# Generated by Django 4.0.6 on 2022-07-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_image_type_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='type_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_jpg',
            field=models.ImageField(blank=True, upload_to='sliderimg/', verbose_name='Изображения JPG'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_webp',
            field=models.ImageField(blank=True, upload_to='slidrimg/', verbose_name='Изображения WEBP'),
        ),
    ]
