# Generated by Django 4.0.6 on 2022-07-22 08:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_image_image_remove_image_type_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='type_description',
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок описания'),
        ),
        migrations.AlterField(
            model_name='description',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст описания'),
        ),
    ]
