# Generated by Django 4.0.2 on 2022-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_description_type_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.ManyToManyField(blank=True, to='pages.Description', verbose_name='Описания'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ManyToManyField(blank=True, to='pages.Image', verbose_name='Изображения'),
        ),
    ]
