# Generated by Django 4.0.6 on 2022-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_img_jpeg', models.ImageField(upload_to='sliderimg/')),
                ('index_img_webp', models.ImageField(upload_to='sliderimg/')),
                ('index_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('index_text', models.TextField(max_length=200, verbose_name='Текст')),
                ('index_css', models.CharField(default='-', max_length=200, null=True, verbose_name='CSS класс')),
            ],
            options={
                'verbose_name': 'Слайд для главной',
                'verbose_name_plural': 'Слайды для главной',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_dt', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('order_phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('order_mail', models.CharField(max_length=200, verbose_name='Почта')),
                ('order_text', models.TextField(max_length=1000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
