# Generated by Django 4.0.6 on 2022-07-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_up', models.CharField(max_length=500, verbose_name='Верхнее описание')),
                ('desc_down', models.CharField(max_length=500, verbose_name='Нижнее описание')),
            ],
            options={
                'verbose_name': 'Описание для нижних карточек',
                'verbose_name_plural': 'Описание для нижних карточек',
            },
        ),
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_img_jpeg', models.ImageField(upload_to='sliderimg/')),
                ('index_img_webp', models.ImageField(upload_to='sliderimg/')),
            ],
            options={
                'verbose_name': 'Слайд для главной',
                'verbose_name_plural': 'Слайды для главной',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопросы клиентов',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='UpCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_head', models.CharField(max_length=500, verbose_name='Верхнее описание')),
                ('desc_mid', models.CharField(max_length=500, verbose_name='Срединное описание')),
                ('desc_bot', models.CharField(max_length=500, verbose_name='Нижнее описание')),
            ],
            options={
                'verbose_name': 'Описание для верха',
                'verbose_name_plural': 'Описание для верха',
            },
        ),
    ]
