# Generated by Django 4.0.6 on 2022-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dt',
            new_name='order_dt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='order_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='order_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AddField(
            model_name='order',
            name='order_mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_text',
            field=models.TextField(max_length=1000, null=True, verbose_name='Сообщение'),
        ),
    ]
