# Generated by Django 4.0.6 on 2022-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_dt_order_order_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_dt',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_text',
        ),
        migrations.AddField(
            model_name='order',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Сообщение'),
        ),
    ]
