# Generated by Django 4.0.6 on 2022-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_indexslider_index_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_head', models.CharField(max_length=300, verbose_name='Верхнее описание')),
                ('desc_mid', models.CharField(max_length=300, verbose_name='Срединное описание')),
                ('desc_bot', models.CharField(max_length=300, verbose_name='Нижнее описание')),
            ],
            options={
                'verbose_name': 'Описание для верха',
                'verbose_name_plural': 'Описание для верха',
            },
        ),
    ]
