# Generated by Django 4.0.6 on 2022-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_upcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_up', models.CharField(max_length=500, verbose_name='Верхнее описание')),
                ('desc_down', models.CharField(max_length=500, verbose_name='Нижнее описание')),
            ],
            options={
                'verbose_name': 'Описание для нижних карточек',
                'verbose_name_plural': 'Описание для нижних карточек',
            },
        ),
        migrations.AlterField(
            model_name='upcard',
            name='desc_bot',
            field=models.CharField(max_length=500, verbose_name='Нижнее описание'),
        ),
        migrations.AlterField(
            model_name='upcard',
            name='desc_head',
            field=models.CharField(max_length=500, verbose_name='Верхнее описание'),
        ),
        migrations.AlterField(
            model_name='upcard',
            name='desc_mid',
            field=models.CharField(max_length=500, verbose_name='Срединное описание'),
        ),
    ]
