# Generated by Django 4.0.6 on 2022-07-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_order_dt_order_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.EmailField(blank=True, help_text='adret1224@mail.ru', max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Ivan', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='8 (954) 342-11-23', max_length=12, verbose_name='Телефон'),
        ),
    ]
