# Generated by Django 4.0.6 on 2022-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_order_mail_alter_order_name_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+7', max_length=12, verbose_name='Телефон'),
        ),
    ]
