# Generated by Django 4.0.6 on 2022-07-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
